### ISSUE TITLE
命令行新建的项目启动失败

### ISSUE THREAD

**Issue by ygtzz** [tal-tech/create-electron-app#1]
![image](https://user-images.githubusercontent.com/5249100/102861036-e6d67000-4469-11eb-968d-5fc18fdae5ea.png)

**Comment by ygtzz** [comment]
OS:      win10
Node:  v12.19.0

**Comment by ivyhaswell** [comment]
@ygtzz 可以提供具体的操作流程吗？我走了一遍没有复现出来

**Comment by ivyhaswell** [comment]
0.2.0版本已经修复
